In [1]:
from transformers import AutoTokenizer, AutoModelForCausalLM
tokenizer = AutoTokenizer.from_pretrained("distilgpt2") 

model = AutoModelForCausalLM.from_pretrained("distilgpt2", output_hidden_states=True)

/Users/aasibipin/aidi-2001/.venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
The following generation flags are not valid and may be ignored: ['output_hidden_states']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Loading weights: 100%|██████████| 76/76 [00:00<00:00, 1557.28it/s, Materializing param=transformer.wte.weight]            
GPT2LMHeadModel LOAD REPORT from: distilgpt2
Key                                        | Status     |  | 
-------------------------------------------+------------+--+-
transformer.h.{0, 1, 2, 3, 4, 5}.attn.bias | UNEXPECTED |  | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.


In [16]:
tokenizer = AutoTokenizer.from_pretrained("bert-base-cased")

sequence = "The Shawshank"
tokens = tokenizer.tokenize(sequence)

print(tokens)

['The', 'Shaw', '##shan', '##k']


In [34]:
tokenizer = AutoTokenizer.from_pretrained("distilgpt2")

sequence = "The pilgrimage"
tokens = tokenizer.tokenize(sequence)

print(tokens)
ids = tokenizer.convert_tokens_to_ids(tokens)
print(ids)

['The', 'Ġpilgrimage']
[464, 36068]


In [35]:
# Tokenize the input string
input = tokenizer.encode(sequence, return_tensors="pt")
print(input)


tensor([[  464, 36068]])


In [36]:

# Run the model
output = model.generate(input, max_length=5, do_sample=False)



The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


In [37]:
output

tensor([[  464, 36068,   284,   262,  7439]])

In [38]:
# Print the output
print('\n',tokenizer.decode(output[0]))


 The pilgrimage to the Holy


In [101]:
# Print the token ides (of the input and output)
output

tensor([[  464, 18193,  1477,   962, 34433]])

## From words to vectors and back

In [102]:
# Print the input token ids
text = "The Shawshank"
input = tokenizer(text, return_tensors="pt")['input_ids']
input

tensor([[  464, 18193,  1477,   962]])

In [ ]:
tokenizer.convert_ids_to_tokens(input[0])

['The', 'ĠShaw', 'sh', 'ank']

## Breathe meaning into numbers (Embedding)

In [ ]:
# This is the embedding matrix of the model
model.transformer.wte # Dimensions are: (Number of tokens in vocabulary, dimension of model)

Embedding(50257, 768)

In [ ]:
# Get the embedding vector of token # 464 ('The')
model.transformer.wte(torch.tensor(464))

In [108]:
text = "The chicken didn't cross the road because it was"

# Tokenize the input string
input = tokenizer.encode(text, return_tensors="pt")

# Run the model
output = model.generate(input, max_length=20, do_sample=True)

# Print the output
print('\n',tokenizer.decode(output[0]))

Setting `pad_token_id` to 50256 (first `eos_token_id`) to generate sequence



 The chicken didn't cross the road because it was in the street. The driver then asked if the
